### PR TITLE
update package-lock.json

### LINKED ISSUE #68: Update frontend develop package-lock.json
Only to update this file: package-lock.json

### PR DESCRIPTION
**Pull request by acampsm**
closes #68 

minor changes to package-lock.json

### CODE REVIEW

**Comment by aicampbell** [comment]
Why are there commits dating back to 23rd January?
Only one file was even changed...

**Comment by acampsm** [comment]
> 
> 
> Why are there commits dating back to 23rd January?
> Only one file was even changed...

I'm not sure, maybe the merges from different repositories could do this.

**Comment by dsanchez-cells** [comment]
We will review it on our end next week. Alex may be right that some of the merges we've done on our side can be behind this, we'll try to clean it up.

**Comment by dsanchez-cells** [comment]
Closing after merging #74

**Pull request closed without merging**
